---

# Configure local box as a workstation

- hosts: localhost
  tasks:
    - name: packages
      dnf: state=installed name={{item}}
      with_items:
        - ShellCheck
        - adobe-source-code-pro-fonts
        - autoconf
        - automake
        - bash
        - bash-completion
        - blueberry
        - cmake
        - clang
        - curl
        - dnf-plugins-core
        - emacs
        - fedora-packager
        - firefox
        - gcc-c++
        - gdb
        - git
        - gitg
        - gnome-terminal
        - irssi
        - isync
        - jq
        - krb5-workstation
        - libicu-devel
        - libunwind-devel
        - libvirt-client # virsh
        - lldb-devel
        - llvm
        - lttng-ust-devel
        - make
        - mercurial
        - mutt
        - offlineimap
        - openssh-clients
        - pandoc
        - podman
        - proselint
        - python3
        - the_silver_searcher # ag
        - tar
        - texlive-latex-bin-bin # /usr/bin/pdflatex
        - tmux
        - valgrind
        - vim-enhanced
        - virt-manager
        - wget
        - xterm
        - zip
