" don't worry about vi-compatibility
set nocompatible

" indentation
set expandtab
set shiftwidth=4
set tabstop=4
set autoindent
set smartindent

set number
set relativenumber

set ruler

set incsearch
set ignorecase

filetype plugin on
autocmd BufNewFile,BufRead *.md set filetype=markdown
autocmd BufNewFile,BufRead *.targets set filetype=xml
autocmd BufNewFile,BufRead *.props set filetype=xml
autocmd BufNewFile,BufRead *.pkgproj set filetype=xml
autocmd BufNewFile,BufRead *.csproj set filetype=xml
autocmd BufNewFile,BufRead *.proj set filetype=xml
autocmd BufReadCmd *.nupkg call zip#Browse(expand("<amatch>"))
syntax enable

set background=dark
colorscheme solarized
