" don't worry about vi-compatibility
set nocompatible

" indentation
set expandtab
set shiftwidth=4
set tabstop=4
set autoindent
set smartindent

set number
set relativenumber

set ruler

set incsearch
set ignorecase

filetype plugin on
autocmd BufNewFile,BufRead *.md set filetype=markdown
syntax enable

set background=dark
colorscheme solarized
