# -*- mode: snippet -*-
# name: dockerfile
# key: dockerfile
# expand-env: ((yas-indent-line 'fixed))
# --
FROM fedora:30

RUN dnf install --setopt tsflags=nodocs --refresh -y \\
    make \\
    python3 \\
    tar \\
    wget \\
    which \\
    dnf upgrade -y && \\
    dnf clean all -y

CMD $0
